# Generated by Django 3.2.5 on 2022-03-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=20, verbose_name='文件名')),
                ('belongtofolder', models.CharField(default='', max_length=20, verbose_name='文件所属文件夹')),
                ('filesize', models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='文件大小')),
                ('filetype', models.CharField(default='', max_length=10, verbose_name='文件类型')),
                ('downloadtimes', models.IntegerField(default=0, verbose_name='文件下载次数')),
            ],
        ),
    ]
