# Generated by Django 3.2.5 on 2022-03-11 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='related_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder.folder'),
        ),
    ]
