# Generated by Django 4.0.2 on 2022-03-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='belongtofolder',
            new_name='belong_to_folder',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='downloadtimes',
            new_name='download_times',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='filename',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='filesize',
            new_name='file_size',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='filetype',
            new_name='file_type',
        ),
    ]
