# Generated by Django 2.2.5 on 2022-03-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='belongtofolder',
            field=models.CharField(default='', max_length=20, verbose_name='文件所属文件夹'),
        ),
        migrations.AddField(
            model_name='file',
            name='downloadtimes',
            field=models.IntegerField(default='', verbose_name='文件下载次数'),
        ),
        migrations.AddField(
            model_name='file',
            name='filesize',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='文件大小'),
        ),
        migrations.AddField(
            model_name='file',
            name='filetype',
            field=models.CharField(default='', max_length=10, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
