# Generated by Django 4.0.2 on 2022-03-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=20, verbose_name='文件夹名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exist_time', models.IntegerField(verbose_name='存在时间')),
            ],
        ),
        migrations.CreateModel(
            name='ShareFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=20, verbose_name='文件夹名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exist_time', models.IntegerField(verbose_name='存在时间')),
                ('sharecode', models.CharField(max_length=20, verbose_name='分享码')),
            ],
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
