# Generated by Django 2.2.5 on 2022-03-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_commonfolder_sharefolder_delete_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=20, verbose_name='文件夹名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exist_time', models.IntegerField(verbose_name='存在时间')),
                ('foldercreater', models.CharField(max_length=20, verbose_name='文件夹创建者')),
                ('sharecode', models.CharField(max_length=20, verbose_name='分享码')),
                ('folderpermission', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CommonFolder',
        ),
        migrations.DeleteModel(
            name='ShareFolder',
        ),
    ]
