# Generated by Django 4.0.2 on 2022-03-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0004_alter_folder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='foldercreater',
            new_name='folder_creater',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='foldername',
            new_name='folder_name',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='folderpermission',
            new_name='folder_permission',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='sharecode',
            new_name='share_code',
        ),
    ]
